//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchrotronHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmpID { get; set; }
        public string SLRI_ID { get; set; }
        public string CardID { get; set; }
        public Nullable<int> Orders { get; set; }
        public string FirstNameTH { get; set; }
        public string LastNameTH { get; set; }
        public string FirstNameEN { get; set; }
        public string MiddleNameEN { get; set; }
        public string LastNameEN { get; set; }
        public string TitleTH { get; set; }
        public string TitleEN { get; set; }
        public string EmployeeLevelID { get; set; }
        public string EmployeeLevel { get; set; }
        public string DepID { get; set; }
        public string Department { get; set; }
        public string SectorID { get; set; }
        public string Sector { get; set; }
        public string Position { get; set; }
        public string ReportPosition { get; set; }
        public string ContractID { get; set; }
        public string Contract { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Status { get; set; }
        public string PersonalID { get; set; }
        public string SocialSecurity { get; set; }
        public string Taxpayer { get; set; }
        public string FundNo { get; set; }
        public string PassportID { get; set; }
        public string Stafflevel { get; set; }
        public string StaffType { get; set; }
        public Nullable<System.DateTime> SWD { get; set; }
        public Nullable<System.DateTime> GWD { get; set; }
        public string Pic { get; set; }
        public string WageCalculation { get; set; }
        public string HouseNo { get; set; }
        public string HouseNo_ht { get; set; }
        public string Building { get; set; }
        public string Building_ht { get; set; }
        public string Soi { get; set; }
        public string Soi_ht { get; set; }
        public string Street { get; set; }
        public string Street_ht { get; set; }
        public string Province { get; set; }
        public string Province_ht { get; set; }
        public string District { get; set; }
        public string District_ht { get; set; }
        public string SubDistrict { get; set; }
        public string SubDistrict_ht { get; set; }
        public string ZIPcode { get; set; }
        public string ZIPcode_ht { get; set; }
        public string Country { get; set; }
        public string Country_ht { get; set; }
        public string Phone { get; set; }
        public string Phone_ht { get; set; }
        public string Mobile { get; set; }
        public string InternalPhone { get; set; }
        public string NickName { get; set; }
        public string BirthPlace { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Race { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string BloodType { get; set; }
        public string Appearance { get; set; }
        public string Earmark { get; set; }
        public string email { get; set; }
        public string WebSite { get; set; }
        public string Facebook { get; set; }
        public string Instragram { get; set; }
        public string LineID { get; set; }
        public string MilitaryStatus { get; set; }
        public string CongenitalDisease { get; set; }
        public string Remark { get; set; }
        public string Hobby { get; set; }
        public string Sport { get; set; }
        public bool Smoking { get; set; }
        public string Typewriter { get; set; }
        public string DriverLicense { get; set; }
        public string MotorcycleDriverLicense { get; set; }
        public Nullable<decimal> ToeicScore { get; set; }
        public Nullable<decimal> ToeflScore { get; set; }
        public string AccountNo { get; set; }
        public string AccountBank { get; set; }
        public bool ForeignerStatus { get; set; }
        public string FamilyStatus { get; set; }
        public Nullable<int> DirectorID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
    }
}
