//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchrotronHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JAMaster
    {
        public int id { get; set; }
        public string jaYear { get; set; }
        public Nullable<int> masterEmpId { get; set; }
        public string fullname { get; set; }
        public string education { get; set; }
        public string major { get; set; }
        public string experience { get; set; }
        public string empPosition { get; set; }
        public string empSection { get; set; }
        public string empDepartment { get; set; }
        public Nullable<System.DateTime> JACreatedDate { get; set; }
        public string JobPurpose { get; set; }
        public Nullable<decimal> KPIWeight { get; set; }
        public Nullable<decimal> keyResponsibilitiesWeight { get; set; }
        public Nullable<decimal> secondaryActivitiesWeight { get; set; }
        public Nullable<decimal> otherActivitiesWeight { get; set; }
        public Nullable<decimal> extraWeight { get; set; }
        public string competenciesKnowledge { get; set; }
        public string competenciesSkill { get; set; }
        public string competenciesAbilities { get; set; }
        public string other { get; set; }
        public string insideDepartment { get; set; }
        public string outsideDepartment { get; set; }
        public string outsideSLRI { get; set; }
        public string jaStatus { get; set; }
        public Nullable<System.DateTime> submittedDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string createdByIP { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string updatedByIp { get; set; }
    }
}
