//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchrotronHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JAManagerFlowApprove
    {
        public int id { get; set; }
        public string mangerEmpID { get; set; }
        public string firstNameTH { get; set; }
        public Nullable<int> depID { get; set; }
        public string department { get; set; }
        public string mangerLV0ID { get; set; }
        public string mangerLV0FirstName { get; set; }
        public string mangerLV0LastName { get; set; }
        public string mangerLV1ID { get; set; }
        public string mangerLV1FirstName { get; set; }
        public string mangerLV1LastName { get; set; }
        public string isActive { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    }
}
