//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchrotronHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDMasterEmp
    {
        public int id { get; set; }
        public string empId { get; set; }
        public Nullable<int> jdId { get; set; }
        public string isActive { get; set; }
        public string cretedBy { get; set; }
        public Nullable<System.DateTime> cretedDate { get; set; }
        public string cretedByIp { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string updatedByIp { get; set; }
    }
}
