//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchrotronHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDMaster
    {
        public int id { get; set; }
        public string jdPosition { get; set; }
        public string jdDepartment { get; set; }
        public string jdPurpose { get; set; }
        public string keyResponsibilities { get; set; }
        public Nullable<decimal> keyResponsibilitiesWeight { get; set; }
        public string secondaryActivities { get; set; }
        public Nullable<decimal> secondaryActivitiesWeight { get; set; }
        public string otherActivities { get; set; }
        public Nullable<decimal> otherActivitiesWeight { get; set; }
        public string positionOfDirectSuperior { get; set; }
        public string positionOfDirectSubordinate { get; set; }
        public Nullable<int> amountOfDirectSubordinate { get; set; }
        public Nullable<int> amountSubordinate { get; set; }
        public string insideDepartment { get; set; }
        public string outsideDepartment { get; set; }
        public string outsideSLRI { get; set; }
        public string EduBackground { get; set; }
        public string major { get; set; }
        public string proExp { get; set; }
        public string competenciesKnowledge { get; set; }
        public string competenciesSkill { get; set; }
        public string competenciesAbilities { get; set; }
        public string other { get; set; }
        public string jdStatus { get; set; }
        public string cretedBy { get; set; }
        public Nullable<System.DateTime> cretedDate { get; set; }
        public string cretedByIp { get; set; }
        public string updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public string updatedByIp { get; set; }
    }
}
