//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchrotronHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JDMasterSub
    {
        public int id { get; set; }
        public Nullable<int> jdMasterId { get; set; }
        public string descriptionSub { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string subType { get; set; }
        public string isStatus { get; set; }
    }
}
