//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchrotronHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIJoin
    {
        public int id { get; set; }
        public Nullable<int> KPIId { get; set; }
        public Nullable<int> accountId { get; set; }
        public Nullable<decimal> percentJoin { get; set; }
        public Nullable<decimal> percentJoinScore { get; set; }
        public Nullable<decimal> percentWorkload { get; set; }
        public Nullable<decimal> percentWorkloadScore { get; set; }
        public string isStatus { get; set; }
    }
}
