//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchrotronHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPIResponsible
    {
        public int id { get; set; }
        public Nullable<int> PercentManagerId { get; set; }
        public Nullable<int> attributeId { get; set; }
        public Nullable<int> KPIYearControlId { get; set; }
        public Nullable<int> employeeId { get; set; }
        public Nullable<decimal> scoreAttribute { get; set; }
        public string Remark { get; set; }
        public string isActive { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
    }
}
