//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchrotronHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class masterDDL
    {
        public int id { get; set; }
        public string ddlType { get; set; }
        public string ddlValue { get; set; }
        public string ddlDisplay { get; set; }
        public string ddlStatus { get; set; }
        public Nullable<int> ddlOrder { get; set; }
    }
}
