//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchrotronHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class masterAtribute
    {
        public int id { get; set; }
        public string attributeName { get; set; }
        public string attributeDetail { get; set; }
        public Nullable<decimal> attributePercent { get; set; }
        public string attributeStatus { get; set; }
    }
}
