//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SynchrotronHR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionKPIDisplay
    {
        public int id { get; set; }
        public Nullable<int> yid { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> SubGroupId { get; set; }
        public Nullable<int> KPITypeId { get; set; }
        public Nullable<int> KPITypeSubId { get; set; }
        public string isActive { get; set; }
    }
}
