//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SynchrotronHR.Resources.home", typeof(home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviate.
        /// </summary>
        public static string AbbreviateEN {
            get {
                return ResourceManager.GetString("AbbreviateEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviate in Thai.
        /// </summary>
        public static string AbbreviateTH {
            get {
                return ResourceManager.GetString("AbbreviateTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission year.
        /// </summary>
        public static string AdmissionYear {
            get {
                return ResourceManager.GetString("AdmissionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Back to List.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Branch {
            get {
                return ResourceManager.GetString("Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Full Screen.
        /// </summary>
        public static string CloseFullScreen {
            get {
                return ResourceManager.GetString("CloseFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Right ©2019 Human Resources Information System.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Countries2Digit {
            get {
                return ResourceManager.GetString("Countries2Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries Code.
        /// </summary>
        public static string CountriesCode {
            get {
                return ResourceManager.GetString("CountriesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name.
        /// </summary>
        public static string CountriesEN {
            get {
                return ResourceManager.GetString("CountriesEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countrie name.
        /// </summary>
        public static string CountriesTH {
            get {
                return ResourceManager.GetString("CountriesTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreateBy {
            get {
                return ResourceManager.GetString("CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Add New.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DelSure {
            get {
                return ResourceManager.GetString("DelSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name.
        /// </summary>
        public static string DepNameEN {
            get {
                return ResourceManager.GetString("DepNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name.
        /// </summary>
        public static string DepNameTH {
            get {
                return ResourceManager.GetString("DepNameTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Districts.
        /// </summary>
        public static string Districts {
            get {
                return ResourceManager.GetString("Districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name.
        /// </summary>
        public static string DistrictsEN {
            get {
                return ResourceManager.GetString("DistrictsEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District name.
        /// </summary>
        public static string DistrictsTH {
            get {
                return ResourceManager.GetString("DistrictsTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Roles.
        /// </summary>
        public static string EditRoles {
            get {
                return ResourceManager.GetString("EditRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullScreen.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPA.
        /// </summary>
        public static string GPA {
            get {
                return ResourceManager.GetString("GPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation year.
        /// </summary>
        public static string GraduationYear {
            get {
                return ResourceManager.GetString("GraduationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Resources Information System.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string Institution {
            get {
                return ResourceManager.GetString("Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name.
        /// </summary>
        public static string LevelEN {
            get {
                return ResourceManager.GetString("LevelEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified by.
        /// </summary>
        public static string ModifyBy {
            get {
                return ResourceManager.GetString("ModifyBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string ModifyDate {
            get {
                return ResourceManager.GetString("ModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name.
        /// </summary>
        public static string PositionEN {
            get {
                return ResourceManager.GetString("PositionEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position name.
        /// </summary>
        public static string PositionTH {
            get {
                return ResourceManager.GetString("PositionTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief Officer.
        /// </summary>
        public static string PosUpright {
            get {
                return ResourceManager.GetString("PosUpright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name.
        /// </summary>
        public static string ProvinceEN {
            get {
                return ResourceManager.GetString("ProvinceEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinces.
        /// </summary>
        public static string Provinces {
            get {
                return ResourceManager.GetString("Provinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete province.
        /// </summary>
        public static string ProvincesDel {
            get {
                return ResourceManager.GetString("ProvincesDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province details.
        /// </summary>
        public static string ProvincesDetails {
            get {
                return ResourceManager.GetString("ProvincesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Edit Province.
        /// </summary>
        public static string ProvincesEdit {
            get {
                return ResourceManager.GetString("ProvincesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provinces name.
        /// </summary>
        public static string ProvinceTH {
            get {
                return ResourceManager.GetString("ProvinceTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PWS {
            get {
                return ResourceManager.GetString("PWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Please select a Department--.
        /// </summary>
        public static string SelDep {
            get {
                return ResourceManager.GetString("SelDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Please select a District--.
        /// </summary>
        public static string SelDistrict {
            get {
                return ResourceManager.GetString("SelDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Please select a Position--.
        /// </summary>
        public static string SelPostion {
            get {
                return ResourceManager.GetString("SelPostion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Please select a Province--.
        /// </summary>
        public static string SelProvince {
            get {
                return ResourceManager.GetString("SelProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub department.
        /// </summary>
        public static string SubDep {
            get {
                return ResourceManager.GetString("SubDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdistricts.
        /// </summary>
        public static string Subdistricts {
            get {
                return ResourceManager.GetString("Subdistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English name.
        /// </summary>
        public static string SubdistrictsEN {
            get {
                return ResourceManager.GetString("SubdistrictsEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdistrict name.
        /// </summary>
        public static string SubdistrictsTH {
            get {
                return ResourceManager.GetString("SubdistrictsTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subordinate.
        /// </summary>
        public static string Subordinate {
            get {
                return ResourceManager.GetString("Subordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleEN {
            get {
                return ResourceManager.GetString("TitleEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        public static string Titles {
            get {
                return ResourceManager.GetString("Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in Thai.
        /// </summary>
        public static string TitleTH {
            get {
                return ResourceManager.GetString("TitleTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upright.
        /// </summary>
        public static string Upright {
            get {
                return ResourceManager.GetString("Upright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
